[package]
name = "vuln_pdf_parser"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.0"
lopdf = "0.26.0"
pdf-extract = "0.6.3"
regex = "1"
log = "0.4.14"
simple_logger = "2.1.0"
